/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 80
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_escaped_sequence = 1,
  aux_sym_fenced_code_block_token1 = 2,
  sym_code_language = 3,
  anon_sym_BQUOTE = 4,
  aux_sym_inline_code_token1 = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  sym_citation_content = 8,
  anon_sym_LBRACE_AT = 9,
  anon_sym_RBRACE = 10,
  aux_sym_cross_ref_target_token1 = 11,
  anon_sym_LBRACE_POUND = 12,
  anon_sym_DOLLAR = 13,
  sym_math_expression = 14,
  sym_component_text = 15,
  anon_sym_LT = 16,
  anon_sym_GT = 17,
  anon_sym_LT_SLASH = 18,
  anon_sym_SLASH_GT = 19,
  sym_tag_name = 20,
  anon_sym_EQ = 21,
  anon_sym_EQ_LBRACE_LBRACE = 22,
  anon_sym_RBRACE_RBRACE = 23,
  sym_attribute_name = 24,
  anon_sym_DQUOTE = 25,
  anon_sym_SQUOTE = 26,
  sym_double_quoted_content = 27,
  sym_single_quoted_content = 28,
  anon_sym_LBRACE = 29,
  sym_number_literal = 30,
  anon_sym_true = 31,
  anon_sym_false = 32,
  sym_null_literal = 33,
  aux_sym_json_content_token1 = 34,
  sym_variable_path = 35,
  sym_text = 36,
  sym__code_fence_open = 37,
  sym__code_content = 38,
  sym__code_fence_close = 39,
  sym__math_fence_open = 40,
  sym__math_content = 41,
  sym__math_fence_close = 42,
  sym__frontmatter_open = 43,
  sym__frontmatter_content = 44,
  sym__frontmatter_close = 45,
  sym_document = 46,
  sym_frontmatter = 47,
  sym__body_content = 48,
  sym_fenced_code_block = 49,
  sym_inline_code = 50,
  sym_citation = 51,
  sym_cross_reference = 52,
  sym_cross_ref_target = 53,
  sym_display_math = 54,
  sym_math_label = 55,
  sym_math_label_id = 56,
  sym_inline_math = 57,
  sym_component = 58,
  sym__component_child = 59,
  sym_open_tag = 60,
  sym_close_tag = 61,
  sym_self_closing_component = 62,
  sym_attribute = 63,
  sym_boolean_shorthand_attribute = 64,
  sym_string_attribute = 65,
  sym_primitive_attribute = 66,
  sym_json_attribute = 67,
  sym_variable_attribute = 68,
  sym_string_value = 69,
  sym_primitive_value = 70,
  sym__primitive_literal = 71,
  sym_boolean_literal = 72,
  sym_json_content = 73,
  sym_variable_value = 74,
  sym_variable_interpolation = 75,
  aux_sym_document_repeat1 = 76,
  aux_sym_component_repeat1 = 77,
  aux_sym_open_tag_repeat1 = 78,
  aux_sym_json_content_repeat1 = 79,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_escaped_sequence] = "escaped_sequence",
  [aux_sym_fenced_code_block_token1] = "fenced_code_block_token1",
  [sym_code_language] = "code_language",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_inline_code_token1] = "inline_code_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_citation_content] = "citation_content",
  [anon_sym_LBRACE_AT] = "{@",
  [anon_sym_RBRACE] = "}",
  [aux_sym_cross_ref_target_token1] = "cross_ref_target_token1",
  [anon_sym_LBRACE_POUND] = "{#",
  [anon_sym_DOLLAR] = "$",
  [sym_math_expression] = "math_expression",
  [sym_component_text] = "component_text",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [anon_sym_EQ_LBRACE_LBRACE] = "={{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym_double_quoted_content] = "double_quoted_content",
  [sym_single_quoted_content] = "single_quoted_content",
  [anon_sym_LBRACE] = "{",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null_literal] = "null_literal",
  [aux_sym_json_content_token1] = "json_content_token1",
  [sym_variable_path] = "variable_path",
  [sym_text] = "text",
  [sym__code_fence_open] = "code_fence_delimiter",
  [sym__code_content] = "code_content",
  [sym__code_fence_close] = "code_fence_delimiter",
  [sym__math_fence_open] = "math_delimiter",
  [sym__math_content] = "math_content",
  [sym__math_fence_close] = "math_delimiter",
  [sym__frontmatter_open] = "frontmatter_delimiter",
  [sym__frontmatter_content] = "frontmatter_content",
  [sym__frontmatter_close] = "frontmatter_delimiter",
  [sym_document] = "document",
  [sym_frontmatter] = "frontmatter",
  [sym__body_content] = "_body_content",
  [sym_fenced_code_block] = "fenced_code_block",
  [sym_inline_code] = "inline_code",
  [sym_citation] = "citation",
  [sym_cross_reference] = "cross_reference",
  [sym_cross_ref_target] = "cross_ref_target",
  [sym_display_math] = "display_math",
  [sym_math_label] = "math_label",
  [sym_math_label_id] = "math_label_id",
  [sym_inline_math] = "inline_math",
  [sym_component] = "component",
  [sym__component_child] = "_component_child",
  [sym_open_tag] = "open_tag",
  [sym_close_tag] = "close_tag",
  [sym_self_closing_component] = "self_closing_component",
  [sym_attribute] = "attribute",
  [sym_boolean_shorthand_attribute] = "boolean_shorthand_attribute",
  [sym_string_attribute] = "string_attribute",
  [sym_primitive_attribute] = "primitive_attribute",
  [sym_json_attribute] = "json_attribute",
  [sym_variable_attribute] = "variable_attribute",
  [sym_string_value] = "string_value",
  [sym_primitive_value] = "primitive_value",
  [sym__primitive_literal] = "_primitive_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_json_content] = "json_content",
  [sym_variable_value] = "variable_value",
  [sym_variable_interpolation] = "variable_interpolation",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
  [aux_sym_open_tag_repeat1] = "open_tag_repeat1",
  [aux_sym_json_content_repeat1] = "json_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_escaped_sequence] = sym_escaped_sequence,
  [aux_sym_fenced_code_block_token1] = aux_sym_fenced_code_block_token1,
  [sym_code_language] = sym_code_language,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_inline_code_token1] = aux_sym_inline_code_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_citation_content] = sym_citation_content,
  [anon_sym_LBRACE_AT] = anon_sym_LBRACE_AT,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym_cross_ref_target_token1] = aux_sym_cross_ref_target_token1,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_math_expression] = sym_math_expression,
  [sym_component_text] = sym_component_text,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_EQ_LBRACE_LBRACE] = anon_sym_EQ_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_double_quoted_content] = sym_double_quoted_content,
  [sym_single_quoted_content] = sym_single_quoted_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null_literal] = sym_null_literal,
  [aux_sym_json_content_token1] = aux_sym_json_content_token1,
  [sym_variable_path] = sym_variable_path,
  [sym_text] = sym_text,
  [sym__code_fence_open] = sym__code_fence_open,
  [sym__code_content] = sym__code_content,
  [sym__code_fence_close] = sym__code_fence_open,
  [sym__math_fence_open] = sym__math_fence_open,
  [sym__math_content] = sym__math_content,
  [sym__math_fence_close] = sym__math_fence_open,
  [sym__frontmatter_open] = sym__frontmatter_open,
  [sym__frontmatter_content] = sym__frontmatter_content,
  [sym__frontmatter_close] = sym__frontmatter_open,
  [sym_document] = sym_document,
  [sym_frontmatter] = sym_frontmatter,
  [sym__body_content] = sym__body_content,
  [sym_fenced_code_block] = sym_fenced_code_block,
  [sym_inline_code] = sym_inline_code,
  [sym_citation] = sym_citation,
  [sym_cross_reference] = sym_cross_reference,
  [sym_cross_ref_target] = sym_cross_ref_target,
  [sym_display_math] = sym_display_math,
  [sym_math_label] = sym_math_label,
  [sym_math_label_id] = sym_math_label_id,
  [sym_inline_math] = sym_inline_math,
  [sym_component] = sym_component,
  [sym__component_child] = sym__component_child,
  [sym_open_tag] = sym_open_tag,
  [sym_close_tag] = sym_close_tag,
  [sym_self_closing_component] = sym_self_closing_component,
  [sym_attribute] = sym_attribute,
  [sym_boolean_shorthand_attribute] = sym_boolean_shorthand_attribute,
  [sym_string_attribute] = sym_string_attribute,
  [sym_primitive_attribute] = sym_primitive_attribute,
  [sym_json_attribute] = sym_json_attribute,
  [sym_variable_attribute] = sym_variable_attribute,
  [sym_string_value] = sym_string_value,
  [sym_primitive_value] = sym_primitive_value,
  [sym__primitive_literal] = sym__primitive_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_json_content] = sym_json_content,
  [sym_variable_value] = sym_variable_value,
  [sym_variable_interpolation] = sym_variable_interpolation,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
  [aux_sym_open_tag_repeat1] = aux_sym_open_tag_repeat1,
  [aux_sym_json_content_repeat1] = aux_sym_json_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_escaped_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fenced_code_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_code_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_code_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_citation_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cross_ref_target_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_math_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_component_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_double_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_json_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable_path] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__code_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym__code_content] = {
    .visible = true,
    .named = true,
  },
  [sym__code_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym__math_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym__math_content] = {
    .visible = true,
    .named = true,
  },
  [sym__math_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_open] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_content] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_close] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym__body_content] = {
    .visible = false,
    .named = true,
  },
  [sym_fenced_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_code] = {
    .visible = true,
    .named = true,
  },
  [sym_citation] = {
    .visible = true,
    .named = true,
  },
  [sym_cross_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_cross_ref_target] = {
    .visible = true,
    .named = true,
  },
  [sym_display_math] = {
    .visible = true,
    .named = true,
  },
  [sym_math_label] = {
    .visible = true,
    .named = true,
  },
  [sym_math_label_id] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym__component_child] = {
    .visible = false,
    .named = true,
  },
  [sym_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_component] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_shorthand_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_json_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string_value] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_value] = {
    .visible = true,
    .named = true,
  },
  [sym__primitive_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_json_content] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_open_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 7,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 28,
  [33] = 33,
  [34] = 14,
  [35] = 17,
  [36] = 27,
  [37] = 12,
  [38] = 13,
  [39] = 21,
  [40] = 15,
  [41] = 11,
  [42] = 42,
  [43] = 16,
  [44] = 22,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 61,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 71,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 74,
  [100] = 82,
  [101] = 101,
  [102] = 85,
  [103] = 103,
  [104] = 97,
  [105] = 101,
  [106] = 106,
  [107] = 88,
  [108] = 98,
  [109] = 95,
  [110] = 106,
  [111] = 87,
  [112] = 93,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '"', 87,
        '$', 72,
        '\'', 88,
        '-', 32,
        '/', 10,
        '<', 77,
        '=', 83,
        '>', 79,
        '@', 35,
        '[', 51,
        '\\', 12,
        ']', 54,
        '`', 48,
        'f', 59,
        'n', 68,
        't', 65,
        '{', 94,
        '}', 57,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '{') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 87,
        '$', 36,
        '\'', 88,
        '/', 10,
        '=', 83,
        '>', 79,
        '{', 93,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(87);
      if (lookahead == '$') ADVANCE(36);
      if (lookahead == '\'') ADVANCE(88);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '>') ADVANCE(79);
      if (lookahead == '{') ADVANCE(93);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(87);
      if (lookahead == '\\') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(71);
      END_STATE();
    case 7:
      if (lookahead == '$') ADVANCE(73);
      if (lookahead == '<') ADVANCE(77);
      if (lookahead == '[') ADVANCE(52);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead == '`') ADVANCE(48);
      if (lookahead == '{') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 8:
      if (lookahead == '$') ADVANCE(36);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 't') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(82);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(88);
      if (lookahead == '\\') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(81);
      END_STATE();
    case 11:
      if (lookahead == '@') ADVANCE(42);
      END_STATE();
    case 12:
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '$' ||
          lookahead == '\\') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(103);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == '{') ADVANCE(84);
      END_STATE();
    case 24:
      if (lookahead == '}') ADVANCE(42);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(85);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(85);
      if (lookahead != 0) ADVANCE(105);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(106);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 28:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 29:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 30:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(50);
      END_STATE();
    case 31:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(31);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(74);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 35:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 36:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 37:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(92);
      END_STATE();
    case 38:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(90);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '"', 87,
        '$', 72,
        '\'', 88,
        '-', 32,
        '/', 10,
        '<', 77,
        '>', 79,
        '@', 35,
        '[', 51,
        '\\', 12,
        ']', 54,
        '`', 48,
        'f', 59,
        'n', 68,
        't', 65,
        '{', 94,
        '}', 57,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '$') ADVANCE(72);
      if (lookahead == '<') ADVANCE(78);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(111);
      if (lookahead == '`') ADVANCE(48);
      if (lookahead == '{') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_escaped_sequence);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_escaped_sequence);
      if (lookahead == '$' ||
          lookahead == '@' ||
          lookahead == '{') ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead == '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead == '\n') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_code_language);
      if (lookahead == '\n') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_code_language);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_inline_code_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_inline_code_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(76);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(109);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_citation_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          (',' <= lookahead && lookahead <= ';') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LBRACE_AT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'e') ADVANCE(100);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'e') ADVANCE(102);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'l') ADVANCE(104);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'l') ADVANCE(63);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'r') ADVANCE(67);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 's') ADVANCE(61);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == 'u') ADVANCE(64);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_cross_ref_target_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_math_expression);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_component_text);
      if (lookahead == '$') ADVANCE(73);
      if (lookahead == '[') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_component_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '/' &&
          (lookahead < 'A' || 'Z' < lookahead)) ADVANCE(109);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_tag_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '{') ADVANCE(23);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EQ_LBRACE_LBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead == '\\') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead == '\\') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead == '\\') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '#') ADVANCE(71);
      if (lookahead == '@') ADVANCE(56);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '@') ADVANCE(56);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_null_literal);
      if (lookahead == '.' ||
          lookahead == ':') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_json_content_token1);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_json_content_token1);
      if (lookahead == '}') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(106);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_json_content_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_variable_path);
      if (lookahead == '.') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(78);
      if (lookahead == '[') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(111);
      if (lookahead == '{') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '`') ADVANCE(112);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == '{') ADVANCE(43);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '$' ||
          lookahead == '\\') ADVANCE(42);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '[' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(112);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 40, .external_lex_state = 2},
  [2] = {.lex_state = 40, .external_lex_state = 3},
  [3] = {.lex_state = 40, .external_lex_state = 3},
  [4] = {.lex_state = 40, .external_lex_state = 3},
  [5] = {.lex_state = 40, .external_lex_state = 3},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 40, .external_lex_state = 3},
  [12] = {.lex_state = 40, .external_lex_state = 3},
  [13] = {.lex_state = 40, .external_lex_state = 3},
  [14] = {.lex_state = 40, .external_lex_state = 3},
  [15] = {.lex_state = 40, .external_lex_state = 3},
  [16] = {.lex_state = 40, .external_lex_state = 3},
  [17] = {.lex_state = 40, .external_lex_state = 3},
  [18] = {.lex_state = 40, .external_lex_state = 3},
  [19] = {.lex_state = 40, .external_lex_state = 3},
  [20] = {.lex_state = 40, .external_lex_state = 3},
  [21] = {.lex_state = 40, .external_lex_state = 3},
  [22] = {.lex_state = 40, .external_lex_state = 3},
  [23] = {.lex_state = 40, .external_lex_state = 3},
  [24] = {.lex_state = 40, .external_lex_state = 3},
  [25] = {.lex_state = 40, .external_lex_state = 3},
  [26] = {.lex_state = 40, .external_lex_state = 3},
  [27] = {.lex_state = 40, .external_lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 27},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 27},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 27},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 29},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 29},
  [70] = {.lex_state = 29},
  [71] = {.lex_state = 30},
  [72] = {.lex_state = 0, .external_lex_state = 6},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0, .external_lex_state = 7},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 30},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 6},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0, .external_lex_state = 7},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 8},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 31},
  [96] = {.lex_state = 0, .external_lex_state = 9},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 8},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 31},
  [110] = {.lex_state = 8},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 8},
  [113] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_escaped_sequence] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_citation_content] = ACTIONS(1),
    [anon_sym_LBRACE_AT] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym_cross_ref_target_token1] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_EQ_LBRACE_LBRACE] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [sym__code_fence_open] = ACTIONS(1),
    [sym__code_content] = ACTIONS(1),
    [sym__code_fence_close] = ACTIONS(1),
    [sym__math_fence_open] = ACTIONS(1),
    [sym__math_content] = ACTIONS(1),
    [sym__math_fence_close] = ACTIONS(1),
    [sym__frontmatter_open] = ACTIONS(1),
    [sym__frontmatter_content] = ACTIONS(1),
    [sym__frontmatter_close] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(90),
    [sym_frontmatter] = STATE(2),
    [sym__body_content] = STATE(5),
    [sym_fenced_code_block] = STATE(5),
    [sym_inline_code] = STATE(5),
    [sym_citation] = STATE(5),
    [sym_cross_reference] = STATE(5),
    [sym_display_math] = STATE(5),
    [sym_inline_math] = STATE(5),
    [sym_component] = STATE(5),
    [sym_open_tag] = STATE(6),
    [sym_self_closing_component] = STATE(5),
    [sym_variable_interpolation] = STATE(5),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_escaped_sequence] = ACTIONS(5),
    [anon_sym_BQUOTE] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [anon_sym_LBRACE_AT] = ACTIONS(11),
    [anon_sym_DOLLAR] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [sym_text] = ACTIONS(5),
    [sym__code_fence_open] = ACTIONS(19),
    [sym__math_fence_open] = ACTIONS(21),
    [sym__frontmatter_open] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym__code_fence_open,
    ACTIONS(21), 1,
      sym__math_fence_open,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(27), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(4), 11,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [48] = 12,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(43), 1,
      anon_sym_DOLLAR,
    ACTIONS(46), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      sym__code_fence_open,
    ACTIONS(55), 1,
      sym__math_fence_open,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(31), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(3), 11,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [96] = 12,
    ACTIONS(7), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym__code_fence_open,
    ACTIONS(21), 1,
      sym__math_fence_open,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(60), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(3), 11,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [144] = 12,
    ACTIONS(7), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(13), 1,
      anon_sym_DOLLAR,
    ACTIONS(15), 1,
      anon_sym_LT,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym__code_fence_open,
    ACTIONS(21), 1,
      sym__math_fence_open,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(60), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(3), 11,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [192] = 11,
    ACTIONS(64), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(70), 1,
      anon_sym_DOLLAR,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(74), 1,
      anon_sym_LT_SLASH,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_open_tag,
    STATE(17), 1,
      sym_close_tag,
    ACTIONS(62), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(7), 9,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [235] = 11,
    ACTIONS(64), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(70), 1,
      anon_sym_DOLLAR,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(74), 1,
      anon_sym_LT_SLASH,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_open_tag,
    STATE(11), 1,
      sym_close_tag,
    ACTIONS(78), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(10), 9,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [278] = 11,
    ACTIONS(64), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(70), 1,
      anon_sym_DOLLAR,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_open_tag,
    STATE(35), 1,
      sym_close_tag,
    ACTIONS(80), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(9), 9,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [321] = 11,
    ACTIONS(64), 1,
      anon_sym_BQUOTE,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(70), 1,
      anon_sym_DOLLAR,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(82), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_open_tag,
    STATE(41), 1,
      sym_close_tag,
    ACTIONS(78), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(10), 9,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [364] = 10,
    ACTIONS(87), 1,
      anon_sym_BQUOTE,
    ACTIONS(90), 1,
      anon_sym_LBRACK,
    ACTIONS(93), 1,
      anon_sym_LBRACE_AT,
    ACTIONS(96), 1,
      anon_sym_DOLLAR,
    ACTIONS(99), 1,
      anon_sym_LT,
    ACTIONS(102), 1,
      anon_sym_LT_SLASH,
    ACTIONS(104), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_open_tag,
    ACTIONS(84), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(10), 9,
      sym_inline_code,
      sym_citation,
      sym_cross_reference,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [404] = 2,
    ACTIONS(107), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(109), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [420] = 2,
    ACTIONS(111), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(113), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [436] = 2,
    ACTIONS(115), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(117), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [452] = 2,
    ACTIONS(119), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(121), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [468] = 2,
    ACTIONS(123), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(125), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [484] = 2,
    ACTIONS(127), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(129), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [500] = 2,
    ACTIONS(131), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(133), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [516] = 2,
    ACTIONS(135), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(137), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [532] = 2,
    ACTIONS(139), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(141), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [548] = 2,
    ACTIONS(143), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(145), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [564] = 2,
    ACTIONS(147), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(149), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [580] = 2,
    ACTIONS(151), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(153), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [596] = 2,
    ACTIONS(155), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(157), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [612] = 2,
    ACTIONS(159), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(161), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [628] = 2,
    ACTIONS(163), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(165), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [644] = 2,
    ACTIONS(167), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(169), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [660] = 2,
    ACTIONS(171), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(173), 8,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [676] = 5,
    ACTIONS(175), 1,
      anon_sym_GT,
    ACTIONS(177), 1,
      anon_sym_SLASH_GT,
    ACTIONS(179), 1,
      sym_attribute_name,
    STATE(29), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(48), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [697] = 5,
    ACTIONS(179), 1,
      sym_attribute_name,
    ACTIONS(181), 1,
      anon_sym_GT,
    ACTIONS(183), 1,
      anon_sym_SLASH_GT,
    STATE(31), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(48), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [718] = 5,
    ACTIONS(179), 1,
      sym_attribute_name,
    ACTIONS(181), 1,
      anon_sym_GT,
    ACTIONS(185), 1,
      anon_sym_SLASH_GT,
    STATE(31), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(48), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [739] = 4,
    ACTIONS(189), 1,
      sym_attribute_name,
    ACTIONS(187), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(31), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(48), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [758] = 5,
    ACTIONS(175), 1,
      anon_sym_GT,
    ACTIONS(179), 1,
      sym_attribute_name,
    ACTIONS(192), 1,
      anon_sym_SLASH_GT,
    STATE(30), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(48), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [779] = 1,
    ACTIONS(194), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [791] = 1,
    ACTIONS(121), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [803] = 1,
    ACTIONS(133), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [815] = 1,
    ACTIONS(173), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [827] = 1,
    ACTIONS(113), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [839] = 1,
    ACTIONS(117), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [851] = 1,
    ACTIONS(149), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [863] = 1,
    ACTIONS(125), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [875] = 1,
    ACTIONS(109), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [887] = 1,
    ACTIONS(196), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [899] = 1,
    ACTIONS(129), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [911] = 1,
    ACTIONS(153), 9,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE_AT,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [923] = 4,
    ACTIONS(202), 1,
      sym_variable_path,
    ACTIONS(198), 2,
      sym_number_literal,
      sym_null_literal,
    ACTIONS(200), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(80), 2,
      sym__primitive_literal,
      sym_boolean_literal,
  [939] = 6,
    ACTIONS(204), 1,
      anon_sym_DQUOTE,
    ACTIONS(206), 1,
      anon_sym_SQUOTE,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_string_value,
    STATE(51), 1,
      sym_variable_value,
    STATE(52), 1,
      sym_primitive_value,
  [958] = 3,
    ACTIONS(212), 1,
      anon_sym_EQ,
    ACTIONS(214), 1,
      anon_sym_EQ_LBRACE_LBRACE,
    ACTIONS(210), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [970] = 1,
    ACTIONS(216), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [976] = 3,
    ACTIONS(218), 1,
      aux_sym_json_content_token1,
    STATE(53), 1,
      aux_sym_json_content_repeat1,
    STATE(73), 1,
      sym_json_content,
  [986] = 1,
    ACTIONS(220), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [992] = 1,
    ACTIONS(222), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [998] = 1,
    ACTIONS(224), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1004] = 3,
    ACTIONS(226), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(228), 1,
      aux_sym_json_content_token1,
    STATE(56), 1,
      aux_sym_json_content_repeat1,
  [1014] = 1,
    ACTIONS(230), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1020] = 1,
    ACTIONS(232), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1026] = 3,
    ACTIONS(234), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(236), 1,
      aux_sym_json_content_token1,
    STATE(56), 1,
      aux_sym_json_content_repeat1,
  [1036] = 1,
    ACTIONS(239), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1042] = 1,
    ACTIONS(241), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1048] = 1,
    ACTIONS(243), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1054] = 3,
    ACTIONS(245), 1,
      aux_sym_fenced_code_block_token1,
    ACTIONS(247), 1,
      anon_sym_LBRACE_POUND,
    STATE(83), 1,
      sym_math_label,
  [1064] = 2,
    ACTIONS(249), 1,
      aux_sym_cross_ref_target_token1,
    STATE(74), 1,
      sym_cross_ref_target,
  [1071] = 2,
    ACTIONS(251), 1,
      anon_sym_SQUOTE,
    ACTIONS(253), 1,
      sym_single_quoted_content,
  [1078] = 2,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    ACTIONS(255), 1,
      sym_double_quoted_content,
  [1085] = 2,
    ACTIONS(257), 1,
      sym__code_content,
    ACTIONS(259), 1,
      sym__code_fence_close,
  [1092] = 2,
    ACTIONS(261), 1,
      aux_sym_fenced_code_block_token1,
    ACTIONS(263), 1,
      sym_code_language,
  [1099] = 2,
    ACTIONS(265), 1,
      sym__math_content,
    ACTIONS(267), 1,
      sym__math_fence_close,
  [1106] = 2,
    ACTIONS(269), 1,
      sym__code_content,
    ACTIONS(271), 1,
      sym__code_fence_close,
  [1113] = 2,
    ACTIONS(273), 1,
      sym__math_content,
    ACTIONS(275), 1,
      sym__math_fence_close,
  [1120] = 2,
    ACTIONS(277), 1,
      aux_sym_cross_ref_target_token1,
    STATE(92), 1,
      sym_math_label_id,
  [1127] = 2,
    ACTIONS(249), 1,
      aux_sym_cross_ref_target_token1,
    STATE(99), 1,
      sym_cross_ref_target,
  [1134] = 1,
    ACTIONS(279), 1,
      aux_sym_inline_code_token1,
  [1138] = 1,
    ACTIONS(281), 1,
      sym__code_fence_close,
  [1142] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE_RBRACE,
  [1146] = 1,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
  [1150] = 1,
    ACTIONS(287), 1,
      aux_sym_fenced_code_block_token1,
  [1154] = 1,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
  [1158] = 1,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
  [1162] = 1,
    ACTIONS(291), 1,
      anon_sym_RBRACE,
  [1166] = 1,
    ACTIONS(293), 1,
      anon_sym_RBRACE,
  [1170] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE,
  [1174] = 1,
    ACTIONS(297), 1,
      sym__math_fence_close,
  [1178] = 1,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
  [1182] = 1,
    ACTIONS(301), 1,
      aux_sym_fenced_code_block_token1,
  [1186] = 1,
    ACTIONS(303), 1,
      aux_sym_inline_code_token1,
  [1190] = 1,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
  [1194] = 1,
    ACTIONS(259), 1,
      sym__code_fence_close,
  [1198] = 1,
    ACTIONS(307), 1,
      sym_variable_path,
  [1202] = 1,
    ACTIONS(309), 1,
      sym_citation_content,
  [1206] = 1,
    ACTIONS(267), 1,
      sym__math_fence_close,
  [1210] = 1,
    ACTIONS(311), 1,
      ts_builtin_sym_end,
  [1214] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [1218] = 1,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
  [1222] = 1,
    ACTIONS(317), 1,
      sym_tag_name,
  [1226] = 1,
    ACTIONS(319), 1,
      sym__frontmatter_close,
  [1230] = 1,
    ACTIONS(321), 1,
      sym_math_expression,
  [1234] = 1,
    ACTIONS(323), 1,
      sym__frontmatter_content,
  [1238] = 1,
    ACTIONS(325), 1,
      anon_sym_BQUOTE,
  [1242] = 1,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
  [1246] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
  [1250] = 1,
    ACTIONS(331), 1,
      anon_sym_DOLLAR,
  [1254] = 1,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1258] = 1,
    ACTIONS(335), 1,
      anon_sym_RBRACE,
  [1262] = 1,
    ACTIONS(337), 1,
      aux_sym_fenced_code_block_token1,
  [1266] = 1,
    ACTIONS(339), 1,
      anon_sym_BQUOTE,
  [1270] = 1,
    ACTIONS(341), 1,
      anon_sym_GT,
  [1274] = 1,
    ACTIONS(343), 1,
      sym_tag_name,
  [1278] = 1,
    ACTIONS(345), 1,
      sym_citation_content,
  [1282] = 1,
    ACTIONS(347), 1,
      anon_sym_RBRACK,
  [1286] = 1,
    ACTIONS(349), 1,
      sym_math_expression,
  [1290] = 1,
    ACTIONS(351), 1,
      sym_tag_name,
  [1294] = 1,
    ACTIONS(353), 1,
      sym_variable_path,
  [1298] = 1,
    ACTIONS(355), 1,
      sym_tag_name,
  [1302] = 1,
    ACTIONS(357), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 192,
  [SMALL_STATE(7)] = 235,
  [SMALL_STATE(8)] = 278,
  [SMALL_STATE(9)] = 321,
  [SMALL_STATE(10)] = 364,
  [SMALL_STATE(11)] = 404,
  [SMALL_STATE(12)] = 420,
  [SMALL_STATE(13)] = 436,
  [SMALL_STATE(14)] = 452,
  [SMALL_STATE(15)] = 468,
  [SMALL_STATE(16)] = 484,
  [SMALL_STATE(17)] = 500,
  [SMALL_STATE(18)] = 516,
  [SMALL_STATE(19)] = 532,
  [SMALL_STATE(20)] = 548,
  [SMALL_STATE(21)] = 564,
  [SMALL_STATE(22)] = 580,
  [SMALL_STATE(23)] = 596,
  [SMALL_STATE(24)] = 612,
  [SMALL_STATE(25)] = 628,
  [SMALL_STATE(26)] = 644,
  [SMALL_STATE(27)] = 660,
  [SMALL_STATE(28)] = 676,
  [SMALL_STATE(29)] = 697,
  [SMALL_STATE(30)] = 718,
  [SMALL_STATE(31)] = 739,
  [SMALL_STATE(32)] = 758,
  [SMALL_STATE(33)] = 779,
  [SMALL_STATE(34)] = 791,
  [SMALL_STATE(35)] = 803,
  [SMALL_STATE(36)] = 815,
  [SMALL_STATE(37)] = 827,
  [SMALL_STATE(38)] = 839,
  [SMALL_STATE(39)] = 851,
  [SMALL_STATE(40)] = 863,
  [SMALL_STATE(41)] = 875,
  [SMALL_STATE(42)] = 887,
  [SMALL_STATE(43)] = 899,
  [SMALL_STATE(44)] = 911,
  [SMALL_STATE(45)] = 923,
  [SMALL_STATE(46)] = 939,
  [SMALL_STATE(47)] = 958,
  [SMALL_STATE(48)] = 970,
  [SMALL_STATE(49)] = 976,
  [SMALL_STATE(50)] = 986,
  [SMALL_STATE(51)] = 992,
  [SMALL_STATE(52)] = 998,
  [SMALL_STATE(53)] = 1004,
  [SMALL_STATE(54)] = 1014,
  [SMALL_STATE(55)] = 1020,
  [SMALL_STATE(56)] = 1026,
  [SMALL_STATE(57)] = 1036,
  [SMALL_STATE(58)] = 1042,
  [SMALL_STATE(59)] = 1048,
  [SMALL_STATE(60)] = 1054,
  [SMALL_STATE(61)] = 1064,
  [SMALL_STATE(62)] = 1071,
  [SMALL_STATE(63)] = 1078,
  [SMALL_STATE(64)] = 1085,
  [SMALL_STATE(65)] = 1092,
  [SMALL_STATE(66)] = 1099,
  [SMALL_STATE(67)] = 1106,
  [SMALL_STATE(68)] = 1113,
  [SMALL_STATE(69)] = 1120,
  [SMALL_STATE(70)] = 1127,
  [SMALL_STATE(71)] = 1134,
  [SMALL_STATE(72)] = 1138,
  [SMALL_STATE(73)] = 1142,
  [SMALL_STATE(74)] = 1146,
  [SMALL_STATE(75)] = 1150,
  [SMALL_STATE(76)] = 1154,
  [SMALL_STATE(77)] = 1158,
  [SMALL_STATE(78)] = 1162,
  [SMALL_STATE(79)] = 1166,
  [SMALL_STATE(80)] = 1170,
  [SMALL_STATE(81)] = 1174,
  [SMALL_STATE(82)] = 1178,
  [SMALL_STATE(83)] = 1182,
  [SMALL_STATE(84)] = 1186,
  [SMALL_STATE(85)] = 1190,
  [SMALL_STATE(86)] = 1194,
  [SMALL_STATE(87)] = 1198,
  [SMALL_STATE(88)] = 1202,
  [SMALL_STATE(89)] = 1206,
  [SMALL_STATE(90)] = 1210,
  [SMALL_STATE(91)] = 1214,
  [SMALL_STATE(92)] = 1218,
  [SMALL_STATE(93)] = 1222,
  [SMALL_STATE(94)] = 1226,
  [SMALL_STATE(95)] = 1230,
  [SMALL_STATE(96)] = 1234,
  [SMALL_STATE(97)] = 1238,
  [SMALL_STATE(98)] = 1242,
  [SMALL_STATE(99)] = 1246,
  [SMALL_STATE(100)] = 1250,
  [SMALL_STATE(101)] = 1254,
  [SMALL_STATE(102)] = 1258,
  [SMALL_STATE(103)] = 1262,
  [SMALL_STATE(104)] = 1266,
  [SMALL_STATE(105)] = 1270,
  [SMALL_STATE(106)] = 1274,
  [SMALL_STATE(107)] = 1278,
  [SMALL_STATE(108)] = 1282,
  [SMALL_STATE(109)] = 1286,
  [SMALL_STATE(110)] = 1290,
  [SMALL_STATE(111)] = 1294,
  [SMALL_STATE(112)] = 1298,
  [SMALL_STATE(113)] = 1302,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_citation, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_citation, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cross_reference, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cross_reference, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_component, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_component, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_interpolation, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_interpolation, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_component, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_component, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_tag, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_tag, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 5, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 5, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_code, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_code, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_open_tag_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_open_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_tag, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_tag, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_shorthand_attribute, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_attribute, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_attribute, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_attribute, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_content, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_value, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_attribute, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_json_content_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_content_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_value, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_value, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_value, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_label, 3, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [311] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cross_ref_target, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_label_id, 1, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__code_fence_open = 0,
  ts_external_token__code_content = 1,
  ts_external_token__code_fence_close = 2,
  ts_external_token__math_fence_open = 3,
  ts_external_token__math_content = 4,
  ts_external_token__math_fence_close = 5,
  ts_external_token__frontmatter_open = 6,
  ts_external_token__frontmatter_content = 7,
  ts_external_token__frontmatter_close = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__code_fence_open] = sym__code_fence_open,
  [ts_external_token__code_content] = sym__code_content,
  [ts_external_token__code_fence_close] = sym__code_fence_close,
  [ts_external_token__math_fence_open] = sym__math_fence_open,
  [ts_external_token__math_content] = sym__math_content,
  [ts_external_token__math_fence_close] = sym__math_fence_close,
  [ts_external_token__frontmatter_open] = sym__frontmatter_open,
  [ts_external_token__frontmatter_content] = sym__frontmatter_content,
  [ts_external_token__frontmatter_close] = sym__frontmatter_close,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__code_fence_open] = true,
    [ts_external_token__code_content] = true,
    [ts_external_token__code_fence_close] = true,
    [ts_external_token__math_fence_open] = true,
    [ts_external_token__math_content] = true,
    [ts_external_token__math_fence_close] = true,
    [ts_external_token__frontmatter_open] = true,
    [ts_external_token__frontmatter_content] = true,
    [ts_external_token__frontmatter_close] = true,
  },
  [2] = {
    [ts_external_token__code_fence_open] = true,
    [ts_external_token__math_fence_open] = true,
    [ts_external_token__frontmatter_open] = true,
  },
  [3] = {
    [ts_external_token__code_fence_open] = true,
    [ts_external_token__math_fence_open] = true,
  },
  [4] = {
    [ts_external_token__code_content] = true,
    [ts_external_token__code_fence_close] = true,
  },
  [5] = {
    [ts_external_token__math_content] = true,
    [ts_external_token__math_fence_close] = true,
  },
  [6] = {
    [ts_external_token__code_fence_close] = true,
  },
  [7] = {
    [ts_external_token__math_fence_close] = true,
  },
  [8] = {
    [ts_external_token__frontmatter_close] = true,
  },
  [9] = {
    [ts_external_token__frontmatter_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rdx_external_scanner_create(void);
void tree_sitter_rdx_external_scanner_destroy(void *);
bool tree_sitter_rdx_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rdx_external_scanner_serialize(void *, char *);
void tree_sitter_rdx_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rdx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_rdx_external_scanner_create,
      tree_sitter_rdx_external_scanner_destroy,
      tree_sitter_rdx_external_scanner_scan,
      tree_sitter_rdx_external_scanner_serialize,
      tree_sitter_rdx_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "rdx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
