/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_escaped_sequence = 1,
  aux_sym_fenced_code_block_token1 = 2,
  sym_code_language = 3,
  anon_sym_BQUOTE = 4,
  aux_sym_inline_code_token1 = 5,
  anon_sym_DOLLAR = 6,
  sym_math_expression = 7,
  sym_component_text = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_LT_SLASH = 11,
  anon_sym_SLASH_GT = 12,
  sym_tag_name = 13,
  anon_sym_EQ = 14,
  anon_sym_EQ_LBRACE_LBRACE = 15,
  anon_sym_RBRACE_RBRACE = 16,
  sym_attribute_name = 17,
  anon_sym_DQUOTE = 18,
  anon_sym_SQUOTE = 19,
  sym_double_quoted_content = 20,
  sym_single_quoted_content = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  sym_number_literal = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_null_literal = 27,
  aux_sym_json_content_token1 = 28,
  sym_variable_path = 29,
  sym_text = 30,
  sym__code_fence_open = 31,
  sym__code_content = 32,
  sym__code_fence_close = 33,
  sym__math_fence_open = 34,
  sym__math_content = 35,
  sym__math_fence_close = 36,
  sym__frontmatter_open = 37,
  sym__frontmatter_content = 38,
  sym__frontmatter_close = 39,
  sym_document = 40,
  sym_frontmatter = 41,
  sym__body_content = 42,
  sym_fenced_code_block = 43,
  sym_inline_code = 44,
  sym_display_math = 45,
  sym_inline_math = 46,
  sym_component = 47,
  sym__component_child = 48,
  sym_open_tag = 49,
  sym_close_tag = 50,
  sym_self_closing_component = 51,
  sym_attribute = 52,
  sym_boolean_shorthand_attribute = 53,
  sym_string_attribute = 54,
  sym_primitive_attribute = 55,
  sym_json_attribute = 56,
  sym_variable_attribute = 57,
  sym_string_value = 58,
  sym_primitive_value = 59,
  sym__primitive_literal = 60,
  sym_boolean_literal = 61,
  sym_json_content = 62,
  sym_variable_value = 63,
  sym_variable_interpolation = 64,
  aux_sym_document_repeat1 = 65,
  aux_sym_component_repeat1 = 66,
  aux_sym_open_tag_repeat1 = 67,
  aux_sym_json_content_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_escaped_sequence] = "escaped_sequence",
  [aux_sym_fenced_code_block_token1] = "fenced_code_block_token1",
  [sym_code_language] = "code_language",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_inline_code_token1] = "inline_code_token1",
  [anon_sym_DOLLAR] = "$",
  [sym_math_expression] = "math_expression",
  [sym_component_text] = "component_text",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [anon_sym_EQ_LBRACE_LBRACE] = "={{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym_double_quoted_content] = "double_quoted_content",
  [sym_single_quoted_content] = "single_quoted_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null_literal] = "null_literal",
  [aux_sym_json_content_token1] = "json_content_token1",
  [sym_variable_path] = "variable_path",
  [sym_text] = "text",
  [sym__code_fence_open] = "code_fence_delimiter",
  [sym__code_content] = "code_content",
  [sym__code_fence_close] = "code_fence_delimiter",
  [sym__math_fence_open] = "math_delimiter",
  [sym__math_content] = "math_content",
  [sym__math_fence_close] = "math_delimiter",
  [sym__frontmatter_open] = "frontmatter_delimiter",
  [sym__frontmatter_content] = "frontmatter_content",
  [sym__frontmatter_close] = "frontmatter_delimiter",
  [sym_document] = "document",
  [sym_frontmatter] = "frontmatter",
  [sym__body_content] = "_body_content",
  [sym_fenced_code_block] = "fenced_code_block",
  [sym_inline_code] = "inline_code",
  [sym_display_math] = "display_math",
  [sym_inline_math] = "inline_math",
  [sym_component] = "component",
  [sym__component_child] = "_component_child",
  [sym_open_tag] = "open_tag",
  [sym_close_tag] = "close_tag",
  [sym_self_closing_component] = "self_closing_component",
  [sym_attribute] = "attribute",
  [sym_boolean_shorthand_attribute] = "boolean_shorthand_attribute",
  [sym_string_attribute] = "string_attribute",
  [sym_primitive_attribute] = "primitive_attribute",
  [sym_json_attribute] = "json_attribute",
  [sym_variable_attribute] = "variable_attribute",
  [sym_string_value] = "string_value",
  [sym_primitive_value] = "primitive_value",
  [sym__primitive_literal] = "_primitive_literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_json_content] = "json_content",
  [sym_variable_value] = "variable_value",
  [sym_variable_interpolation] = "variable_interpolation",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
  [aux_sym_open_tag_repeat1] = "open_tag_repeat1",
  [aux_sym_json_content_repeat1] = "json_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_escaped_sequence] = sym_escaped_sequence,
  [aux_sym_fenced_code_block_token1] = aux_sym_fenced_code_block_token1,
  [sym_code_language] = sym_code_language,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_inline_code_token1] = aux_sym_inline_code_token1,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_math_expression] = sym_math_expression,
  [sym_component_text] = sym_component_text,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_EQ_LBRACE_LBRACE] = anon_sym_EQ_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_double_quoted_content] = sym_double_quoted_content,
  [sym_single_quoted_content] = sym_single_quoted_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null_literal] = sym_null_literal,
  [aux_sym_json_content_token1] = aux_sym_json_content_token1,
  [sym_variable_path] = sym_variable_path,
  [sym_text] = sym_text,
  [sym__code_fence_open] = sym__code_fence_open,
  [sym__code_content] = sym__code_content,
  [sym__code_fence_close] = sym__code_fence_open,
  [sym__math_fence_open] = sym__math_fence_open,
  [sym__math_content] = sym__math_content,
  [sym__math_fence_close] = sym__math_fence_open,
  [sym__frontmatter_open] = sym__frontmatter_open,
  [sym__frontmatter_content] = sym__frontmatter_content,
  [sym__frontmatter_close] = sym__frontmatter_open,
  [sym_document] = sym_document,
  [sym_frontmatter] = sym_frontmatter,
  [sym__body_content] = sym__body_content,
  [sym_fenced_code_block] = sym_fenced_code_block,
  [sym_inline_code] = sym_inline_code,
  [sym_display_math] = sym_display_math,
  [sym_inline_math] = sym_inline_math,
  [sym_component] = sym_component,
  [sym__component_child] = sym__component_child,
  [sym_open_tag] = sym_open_tag,
  [sym_close_tag] = sym_close_tag,
  [sym_self_closing_component] = sym_self_closing_component,
  [sym_attribute] = sym_attribute,
  [sym_boolean_shorthand_attribute] = sym_boolean_shorthand_attribute,
  [sym_string_attribute] = sym_string_attribute,
  [sym_primitive_attribute] = sym_primitive_attribute,
  [sym_json_attribute] = sym_json_attribute,
  [sym_variable_attribute] = sym_variable_attribute,
  [sym_string_value] = sym_string_value,
  [sym_primitive_value] = sym_primitive_value,
  [sym__primitive_literal] = sym__primitive_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_json_content] = sym_json_content,
  [sym_variable_value] = sym_variable_value,
  [sym_variable_interpolation] = sym_variable_interpolation,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
  [aux_sym_open_tag_repeat1] = aux_sym_open_tag_repeat1,
  [aux_sym_json_content_repeat1] = aux_sym_json_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_escaped_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fenced_code_block_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_code_language] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_inline_code_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_math_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_component_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_double_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_json_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable_path] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__code_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym__code_content] = {
    .visible = true,
    .named = true,
  },
  [sym__code_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym__math_fence_open] = {
    .visible = true,
    .named = true,
  },
  [sym__math_content] = {
    .visible = true,
    .named = true,
  },
  [sym__math_fence_close] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_open] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_content] = {
    .visible = true,
    .named = true,
  },
  [sym__frontmatter_close] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_frontmatter] = {
    .visible = true,
    .named = true,
  },
  [sym__body_content] = {
    .visible = false,
    .named = true,
  },
  [sym_fenced_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_code] = {
    .visible = true,
    .named = true,
  },
  [sym_display_math] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym__component_child] = {
    .visible = false,
    .named = true,
  },
  [sym_open_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_close_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_component] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_shorthand_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_json_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_string_value] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_value] = {
    .visible = true,
    .named = true,
  },
  [sym__primitive_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_json_content] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_open_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 7,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 14,
  [15] = 12,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 20,
  [31] = 31,
  [32] = 32,
  [33] = 21,
  [34] = 27,
  [35] = 16,
  [36] = 25,
  [37] = 28,
  [38] = 22,
  [39] = 23,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 61,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 72,
  [82] = 73,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 80,
  [88] = 83,
  [89] = 86,
  [90] = 70,
  [91] = 74,
  [92] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 73,
        '$', 47,
        '\'', 74,
        '-', 29,
        '/', 9,
        '<', 52,
        '=', 59,
        '>', 54,
        '\\', 10,
        '`', 44,
        'f', 62,
        'n', 71,
        't', 68,
        '{', 79,
        '}', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(73);
      if (lookahead == '\\') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(48);
      if (lookahead == '<') ADVANCE(52);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '$') ADVANCE(32);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 't') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(58);
      END_STATE();
    case 6:
      if (lookahead == '$') ADVANCE(32);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '=') ADVANCE(59);
      if (lookahead == '>') ADVANCE(54);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 7:
      if (lookahead == '$') ADVANCE(32);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '>') ADVANCE(54);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(74);
      if (lookahead == '\\') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(88);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 21:
      if (lookahead == '{') ADVANCE(60);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == '}') ADVANCE(61);
      END_STATE();
    case 24:
      if (lookahead == '}') ADVANCE(61);
      if (lookahead != 0) ADVANCE(90);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 26:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 27:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(46);
      END_STATE();
    case 28:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(49);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 32:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 33:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 34:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(78);
      END_STATE();
    case 35:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 73,
        '$', 47,
        '\'', 74,
        '-', 29,
        '/', 9,
        '<', 52,
        '>', 54,
        '\\', 10,
        '`', 44,
        'f', 62,
        'n', 71,
        't', 68,
        '{', 79,
        '}', 80,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 36:
      if (eof) ADVANCE(37);
      if (lookahead == '$') ADVANCE(47);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead == '`') ADVANCE(44);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0) ADVANCE(97);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escaped_sequence);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_escaped_sequence);
      if (lookahead == '$' ||
          lookahead == '{') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead == '\n') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_fenced_code_block_token1);
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_code_language);
      if (lookahead == '\n') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_code_language);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_inline_code_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_inline_code_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_math_expression);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_component_text);
      if (lookahead == '$') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_component_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(55);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '/' &&
          (lookahead < 'A' || 'Z' < lookahead)) ADVANCE(94);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_tag_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '{') ADVANCE(21);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ_LBRACE_LBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'a') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'e') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'e') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'l') ADVANCE(69);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'l') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'l') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'r') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 's') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'u') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == 'u') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead == '\\') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_double_quoted_content);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead == '\\') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_single_quoted_content);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_null_literal);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_json_content_token1);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_json_content_token1);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_json_content_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_variable_path);
      if (lookahead == '.') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(96);
      if (lookahead == '{') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '`') ADVANCE(97);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\\') ADVANCE(38);
      if (lookahead == '{') ADVANCE(39);
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '`' &&
          lookahead != '{') ADVANCE(97);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 36, .external_lex_state = 2},
  [2] = {.lex_state = 36, .external_lex_state = 3},
  [3] = {.lex_state = 36, .external_lex_state = 3},
  [4] = {.lex_state = 36, .external_lex_state = 3},
  [5] = {.lex_state = 36, .external_lex_state = 3},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 36, .external_lex_state = 3},
  [17] = {.lex_state = 36, .external_lex_state = 3},
  [18] = {.lex_state = 36, .external_lex_state = 3},
  [19] = {.lex_state = 36, .external_lex_state = 3},
  [20] = {.lex_state = 36, .external_lex_state = 3},
  [21] = {.lex_state = 36, .external_lex_state = 3},
  [22] = {.lex_state = 36, .external_lex_state = 3},
  [23] = {.lex_state = 36, .external_lex_state = 3},
  [24] = {.lex_state = 36, .external_lex_state = 3},
  [25] = {.lex_state = 36, .external_lex_state = 3},
  [26] = {.lex_state = 36, .external_lex_state = 3},
  [27] = {.lex_state = 36, .external_lex_state = 3},
  [28] = {.lex_state = 36, .external_lex_state = 3},
  [29] = {.lex_state = 36, .external_lex_state = 3},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 25},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 6},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 25},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 6},
  [54] = {.lex_state = 25},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 0, .external_lex_state = 4},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0, .external_lex_state = 5},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0, .external_lex_state = 6},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0, .external_lex_state = 7},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 0, .external_lex_state = 8},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 9},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 27},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 0, .external_lex_state = 6},
  [86] = {.lex_state = 28},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 27},
  [89] = {.lex_state = 28},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 6},
  [92] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_escaped_sequence] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_EQ_LBRACE_LBRACE] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [sym__code_fence_open] = ACTIONS(1),
    [sym__code_content] = ACTIONS(1),
    [sym__code_fence_close] = ACTIONS(1),
    [sym__math_fence_open] = ACTIONS(1),
    [sym__math_content] = ACTIONS(1),
    [sym__math_fence_close] = ACTIONS(1),
    [sym__frontmatter_open] = ACTIONS(1),
    [sym__frontmatter_content] = ACTIONS(1),
    [sym__frontmatter_close] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(76),
    [sym_frontmatter] = STATE(3),
    [sym__body_content] = STATE(4),
    [sym_fenced_code_block] = STATE(4),
    [sym_inline_code] = STATE(4),
    [sym_display_math] = STATE(4),
    [sym_inline_math] = STATE(4),
    [sym_component] = STATE(4),
    [sym_open_tag] = STATE(6),
    [sym_self_closing_component] = STATE(4),
    [sym_variable_interpolation] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_escaped_sequence] = ACTIONS(5),
    [anon_sym_BQUOTE] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [sym_text] = ACTIONS(5),
    [sym__code_fence_open] = ACTIONS(15),
    [sym__math_fence_open] = ACTIONS(17),
    [sym__frontmatter_open] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym__code_fence_open,
    ACTIONS(17), 1,
      sym__math_fence_open,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(23), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(5), 9,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [40] = 10,
    ACTIONS(7), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym__code_fence_open,
    ACTIONS(17), 1,
      sym__math_fence_open,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(27), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(2), 9,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [80] = 10,
    ACTIONS(7), 1,
      anon_sym_BQUOTE,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      sym__code_fence_open,
    ACTIONS(17), 1,
      sym__math_fence_open,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(23), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(5), 9,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [120] = 10,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 1,
      anon_sym_BQUOTE,
    ACTIONS(37), 1,
      anon_sym_DOLLAR,
    ACTIONS(40), 1,
      anon_sym_LT,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(46), 1,
      sym__code_fence_open,
    ACTIONS(49), 1,
      sym__math_fence_open,
    STATE(6), 1,
      sym_open_tag,
    ACTIONS(31), 2,
      sym_escaped_sequence,
      sym_text,
    STATE(5), 9,
      sym__body_content,
      sym_fenced_code_block,
      sym_inline_code,
      sym_display_math,
      sym_inline_math,
      sym_component,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_document_repeat1,
  [160] = 9,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(60), 1,
      anon_sym_LT_SLASH,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_open_tag,
    STATE(16), 1,
      sym_close_tag,
    ACTIONS(52), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(7), 7,
      sym_inline_code,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [195] = 9,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(60), 1,
      anon_sym_LT_SLASH,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_open_tag,
    STATE(25), 1,
      sym_close_tag,
    ACTIONS(64), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(10), 7,
      sym_inline_code,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [230] = 9,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_open_tag,
    STATE(35), 1,
      sym_close_tag,
    ACTIONS(66), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(9), 7,
      sym_inline_code,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [265] = 9,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(56), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_open_tag,
    STATE(36), 1,
      sym_close_tag,
    ACTIONS(64), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(10), 7,
      sym_inline_code,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [300] = 8,
    ACTIONS(73), 1,
      anon_sym_BQUOTE,
    ACTIONS(76), 1,
      anon_sym_DOLLAR,
    ACTIONS(79), 1,
      anon_sym_LT,
    ACTIONS(82), 1,
      anon_sym_LT_SLASH,
    ACTIONS(84), 1,
      anon_sym_LBRACE,
    STATE(8), 1,
      sym_open_tag,
    ACTIONS(70), 2,
      sym_escaped_sequence,
      sym_component_text,
    STATE(10), 7,
      sym_inline_code,
      sym_inline_math,
      sym_component,
      sym__component_child,
      sym_self_closing_component,
      sym_variable_interpolation,
      aux_sym_component_repeat1,
  [332] = 5,
    ACTIONS(87), 1,
      anon_sym_GT,
    ACTIONS(89), 1,
      anon_sym_SLASH_GT,
    ACTIONS(91), 1,
      sym_attribute_name,
    STATE(15), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(52), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [353] = 5,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(93), 1,
      anon_sym_GT,
    ACTIONS(95), 1,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(52), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [374] = 5,
    ACTIONS(87), 1,
      anon_sym_GT,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(97), 1,
      anon_sym_SLASH_GT,
    STATE(12), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(52), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [395] = 4,
    ACTIONS(101), 1,
      sym_attribute_name,
    ACTIONS(99), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(52), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [414] = 5,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(93), 1,
      anon_sym_GT,
    ACTIONS(104), 1,
      anon_sym_SLASH_GT,
    STATE(14), 2,
      sym_attribute,
      aux_sym_open_tag_repeat1,
    STATE(52), 5,
      sym_boolean_shorthand_attribute,
      sym_string_attribute,
      sym_primitive_attribute,
      sym_json_attribute,
      sym_variable_attribute,
  [435] = 2,
    ACTIONS(106), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(108), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [449] = 2,
    ACTIONS(110), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(112), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [463] = 2,
    ACTIONS(114), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(116), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [477] = 2,
    ACTIONS(118), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(120), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [491] = 2,
    ACTIONS(122), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(124), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [505] = 2,
    ACTIONS(126), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(128), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [519] = 2,
    ACTIONS(130), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(132), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [533] = 2,
    ACTIONS(134), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(136), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [547] = 2,
    ACTIONS(138), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(140), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [561] = 2,
    ACTIONS(142), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(144), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [575] = 2,
    ACTIONS(146), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(148), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [589] = 2,
    ACTIONS(150), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(152), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [603] = 2,
    ACTIONS(154), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(156), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [617] = 2,
    ACTIONS(158), 3,
      sym__code_fence_open,
      sym__math_fence_open,
      ts_builtin_sym_end,
    ACTIONS(160), 6,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      anon_sym_LT,
      anon_sym_LBRACE,
      sym_text,
  [631] = 1,
    ACTIONS(124), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [641] = 4,
    ACTIONS(166), 1,
      sym_variable_path,
    ACTIONS(162), 2,
      sym_number_literal,
      sym_null_literal,
    ACTIONS(164), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(66), 2,
      sym__primitive_literal,
      sym_boolean_literal,
  [657] = 1,
    ACTIONS(168), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [667] = 1,
    ACTIONS(128), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [677] = 1,
    ACTIONS(152), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [687] = 1,
    ACTIONS(108), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [697] = 1,
    ACTIONS(144), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [707] = 1,
    ACTIONS(156), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [717] = 1,
    ACTIONS(132), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [727] = 1,
    ACTIONS(136), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [737] = 1,
    ACTIONS(170), 7,
      sym_escaped_sequence,
      anon_sym_BQUOTE,
      anon_sym_DOLLAR,
      sym_component_text,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [747] = 6,
    ACTIONS(172), 1,
      anon_sym_DQUOTE,
    ACTIONS(174), 1,
      anon_sym_SQUOTE,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_string_value,
    STATE(47), 1,
      sym_primitive_value,
    STATE(48), 1,
      sym_variable_value,
  [766] = 3,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(182), 1,
      anon_sym_EQ_LBRACE_LBRACE,
    ACTIONS(178), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [778] = 1,
    ACTIONS(184), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [784] = 1,
    ACTIONS(186), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [790] = 3,
    ACTIONS(188), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(190), 1,
      aux_sym_json_content_token1,
    STATE(49), 1,
      aux_sym_json_content_repeat1,
  [800] = 1,
    ACTIONS(192), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [806] = 1,
    ACTIONS(194), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [812] = 1,
    ACTIONS(196), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [818] = 3,
    ACTIONS(198), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(200), 1,
      aux_sym_json_content_token1,
    STATE(49), 1,
      aux_sym_json_content_repeat1,
  [828] = 1,
    ACTIONS(203), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [834] = 1,
    ACTIONS(205), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [840] = 1,
    ACTIONS(207), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [846] = 1,
    ACTIONS(209), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [852] = 3,
    ACTIONS(211), 1,
      aux_sym_json_content_token1,
    STATE(45), 1,
      aux_sym_json_content_repeat1,
    STATE(84), 1,
      sym_json_content,
  [862] = 2,
    ACTIONS(213), 1,
      anon_sym_DQUOTE,
    ACTIONS(215), 1,
      sym_double_quoted_content,
  [869] = 2,
    ACTIONS(217), 1,
      sym__math_content,
    ACTIONS(219), 1,
      sym__math_fence_close,
  [876] = 2,
    ACTIONS(221), 1,
      sym__code_content,
    ACTIONS(223), 1,
      sym__code_fence_close,
  [883] = 2,
    ACTIONS(213), 1,
      anon_sym_SQUOTE,
    ACTIONS(225), 1,
      sym_single_quoted_content,
  [890] = 2,
    ACTIONS(227), 1,
      aux_sym_fenced_code_block_token1,
    ACTIONS(229), 1,
      sym_code_language,
  [897] = 2,
    ACTIONS(231), 1,
      sym__code_content,
    ACTIONS(233), 1,
      sym__code_fence_close,
  [904] = 1,
    ACTIONS(235), 1,
      anon_sym_RBRACE,
  [908] = 1,
    ACTIONS(237), 1,
      anon_sym_DQUOTE,
  [912] = 1,
    ACTIONS(237), 1,
      anon_sym_SQUOTE,
  [916] = 1,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
  [920] = 1,
    ACTIONS(241), 1,
      anon_sym_RBRACE,
  [924] = 1,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
  [928] = 1,
    ACTIONS(245), 1,
      sym__code_fence_close,
  [932] = 1,
    ACTIONS(247), 1,
      aux_sym_fenced_code_block_token1,
  [936] = 1,
    ACTIONS(249), 1,
      sym__math_fence_close,
  [940] = 1,
    ACTIONS(251), 1,
      sym_tag_name,
  [944] = 1,
    ACTIONS(253), 1,
      sym__frontmatter_close,
  [948] = 1,
    ACTIONS(255), 1,
      anon_sym_BQUOTE,
  [952] = 1,
    ACTIONS(257), 1,
      anon_sym_DOLLAR,
  [956] = 1,
    ACTIONS(259), 1,
      sym_variable_path,
  [960] = 1,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
  [964] = 1,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
  [968] = 1,
    ACTIONS(265), 1,
      sym_tag_name,
  [972] = 1,
    ACTIONS(267), 1,
      aux_sym_fenced_code_block_token1,
  [976] = 1,
    ACTIONS(269), 1,
      sym__frontmatter_content,
  [980] = 1,
    ACTIONS(271), 1,
      anon_sym_GT,
  [984] = 1,
    ACTIONS(273), 1,
      anon_sym_BQUOTE,
  [988] = 1,
    ACTIONS(275), 1,
      anon_sym_DOLLAR,
  [992] = 1,
    ACTIONS(277), 1,
      aux_sym_inline_code_token1,
  [996] = 1,
    ACTIONS(279), 1,
      anon_sym_RBRACE_RBRACE,
  [1000] = 1,
    ACTIONS(233), 1,
      sym__code_fence_close,
  [1004] = 1,
    ACTIONS(281), 1,
      sym_math_expression,
  [1008] = 1,
    ACTIONS(283), 1,
      anon_sym_GT,
  [1012] = 1,
    ACTIONS(285), 1,
      aux_sym_inline_code_token1,
  [1016] = 1,
    ACTIONS(287), 1,
      sym_math_expression,
  [1020] = 1,
    ACTIONS(289), 1,
      sym_tag_name,
  [1024] = 1,
    ACTIONS(291), 1,
      sym_variable_path,
  [1028] = 1,
    ACTIONS(293), 1,
      sym_tag_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 195,
  [SMALL_STATE(8)] = 230,
  [SMALL_STATE(9)] = 265,
  [SMALL_STATE(10)] = 300,
  [SMALL_STATE(11)] = 332,
  [SMALL_STATE(12)] = 353,
  [SMALL_STATE(13)] = 374,
  [SMALL_STATE(14)] = 395,
  [SMALL_STATE(15)] = 414,
  [SMALL_STATE(16)] = 435,
  [SMALL_STATE(17)] = 449,
  [SMALL_STATE(18)] = 463,
  [SMALL_STATE(19)] = 477,
  [SMALL_STATE(20)] = 491,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 519,
  [SMALL_STATE(23)] = 533,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 561,
  [SMALL_STATE(26)] = 575,
  [SMALL_STATE(27)] = 589,
  [SMALL_STATE(28)] = 603,
  [SMALL_STATE(29)] = 617,
  [SMALL_STATE(30)] = 631,
  [SMALL_STATE(31)] = 641,
  [SMALL_STATE(32)] = 657,
  [SMALL_STATE(33)] = 667,
  [SMALL_STATE(34)] = 677,
  [SMALL_STATE(35)] = 687,
  [SMALL_STATE(36)] = 697,
  [SMALL_STATE(37)] = 707,
  [SMALL_STATE(38)] = 717,
  [SMALL_STATE(39)] = 727,
  [SMALL_STATE(40)] = 737,
  [SMALL_STATE(41)] = 747,
  [SMALL_STATE(42)] = 766,
  [SMALL_STATE(43)] = 778,
  [SMALL_STATE(44)] = 784,
  [SMALL_STATE(45)] = 790,
  [SMALL_STATE(46)] = 800,
  [SMALL_STATE(47)] = 806,
  [SMALL_STATE(48)] = 812,
  [SMALL_STATE(49)] = 818,
  [SMALL_STATE(50)] = 828,
  [SMALL_STATE(51)] = 834,
  [SMALL_STATE(52)] = 840,
  [SMALL_STATE(53)] = 846,
  [SMALL_STATE(54)] = 852,
  [SMALL_STATE(55)] = 862,
  [SMALL_STATE(56)] = 869,
  [SMALL_STATE(57)] = 876,
  [SMALL_STATE(58)] = 883,
  [SMALL_STATE(59)] = 890,
  [SMALL_STATE(60)] = 897,
  [SMALL_STATE(61)] = 904,
  [SMALL_STATE(62)] = 908,
  [SMALL_STATE(63)] = 912,
  [SMALL_STATE(64)] = 916,
  [SMALL_STATE(65)] = 920,
  [SMALL_STATE(66)] = 924,
  [SMALL_STATE(67)] = 928,
  [SMALL_STATE(68)] = 932,
  [SMALL_STATE(69)] = 936,
  [SMALL_STATE(70)] = 940,
  [SMALL_STATE(71)] = 944,
  [SMALL_STATE(72)] = 948,
  [SMALL_STATE(73)] = 952,
  [SMALL_STATE(74)] = 956,
  [SMALL_STATE(75)] = 960,
  [SMALL_STATE(76)] = 964,
  [SMALL_STATE(77)] = 968,
  [SMALL_STATE(78)] = 972,
  [SMALL_STATE(79)] = 976,
  [SMALL_STATE(80)] = 980,
  [SMALL_STATE(81)] = 984,
  [SMALL_STATE(82)] = 988,
  [SMALL_STATE(83)] = 992,
  [SMALL_STATE(84)] = 996,
  [SMALL_STATE(85)] = 1000,
  [SMALL_STATE(86)] = 1004,
  [SMALL_STATE(87)] = 1008,
  [SMALL_STATE(88)] = 1012,
  [SMALL_STATE(89)] = 1016,
  [SMALL_STATE(90)] = 1020,
  [SMALL_STATE(91)] = 1024,
  [SMALL_STATE(92)] = 1028,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_open_tag_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_open_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_frontmatter, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_frontmatter, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_code, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_code, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_component, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_component, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_component, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_component, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 4, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fenced_code_block, 5, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fenced_code_block, 5, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_interpolation, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_interpolation, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_tag, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_tag, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_display_math, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_display_math, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_tag, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_open_tag, 4, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_shorthand_attribute, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_attribute, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_attribute, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_content, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_value, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_attribute, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_attribute, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_json_content_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_content_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_value, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_value, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_value, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [263] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__code_fence_open = 0,
  ts_external_token__code_content = 1,
  ts_external_token__code_fence_close = 2,
  ts_external_token__math_fence_open = 3,
  ts_external_token__math_content = 4,
  ts_external_token__math_fence_close = 5,
  ts_external_token__frontmatter_open = 6,
  ts_external_token__frontmatter_content = 7,
  ts_external_token__frontmatter_close = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__code_fence_open] = sym__code_fence_open,
  [ts_external_token__code_content] = sym__code_content,
  [ts_external_token__code_fence_close] = sym__code_fence_close,
  [ts_external_token__math_fence_open] = sym__math_fence_open,
  [ts_external_token__math_content] = sym__math_content,
  [ts_external_token__math_fence_close] = sym__math_fence_close,
  [ts_external_token__frontmatter_open] = sym__frontmatter_open,
  [ts_external_token__frontmatter_content] = sym__frontmatter_content,
  [ts_external_token__frontmatter_close] = sym__frontmatter_close,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__code_fence_open] = true,
    [ts_external_token__code_content] = true,
    [ts_external_token__code_fence_close] = true,
    [ts_external_token__math_fence_open] = true,
    [ts_external_token__math_content] = true,
    [ts_external_token__math_fence_close] = true,
    [ts_external_token__frontmatter_open] = true,
    [ts_external_token__frontmatter_content] = true,
    [ts_external_token__frontmatter_close] = true,
  },
  [2] = {
    [ts_external_token__code_fence_open] = true,
    [ts_external_token__math_fence_open] = true,
    [ts_external_token__frontmatter_open] = true,
  },
  [3] = {
    [ts_external_token__code_fence_open] = true,
    [ts_external_token__math_fence_open] = true,
  },
  [4] = {
    [ts_external_token__math_content] = true,
    [ts_external_token__math_fence_close] = true,
  },
  [5] = {
    [ts_external_token__code_content] = true,
    [ts_external_token__code_fence_close] = true,
  },
  [6] = {
    [ts_external_token__code_fence_close] = true,
  },
  [7] = {
    [ts_external_token__math_fence_close] = true,
  },
  [8] = {
    [ts_external_token__frontmatter_close] = true,
  },
  [9] = {
    [ts_external_token__frontmatter_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_rdx_external_scanner_create(void);
void tree_sitter_rdx_external_scanner_destroy(void *);
bool tree_sitter_rdx_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_rdx_external_scanner_serialize(void *, char *);
void tree_sitter_rdx_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rdx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_rdx_external_scanner_create,
      tree_sitter_rdx_external_scanner_destroy,
      tree_sitter_rdx_external_scanner_scan,
      tree_sitter_rdx_external_scanner_serialize,
      tree_sitter_rdx_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "rdx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
